play.http.secret.key = ${TH_SECRET}

# Cassandra graph backend (JanusGraph + CQL)
db.janusgraph {
  storage.backend = cql
  storage.hostname = ["thehive-db"]
  storage.cql.cluster-name = soc-thehive
  storage.cql.keyspace = thehive
  index.search.backend = lucene
}

# Local file storage
storage {
  provider = localfs
  localfs.directory = /opt/thp/thehive/data
}

# Cortex integration
play.modules.enabled += org.thp.thehive.connector.cortex.CortexConnector
cortex {
  servers = [
    {
      name = "cortex-local"
      url = "http://cortex:9001"
      auth {
        type = "bearer"
        key = ${TH_CORTEX_KEYS}
      }
      wsConfig.ssl.loose.acceptAnyCertificate = true
    }
  ]
  refreshDelay = 5 seconds
  maxRetryOnError = 3
  statusCheckInterval = 1 minute
}
